---
extract_key_facts_task:
  description: Use the PDFSearchTool to extract key facts from the PDF document located
    at {filename}. Focus on identifying significant information that can be used to
    formulate questions and answers.
  expected_output: A list of key facts extracted from the PDF document {filename}.
    This should include the most relevant and important information that can be utilized
    for question generation.
  async_execution: false
  agent: pdf_extractor
generate_questions_and_answers_task:
  description: Create {questions_count} questions and answers from the key facts extracted
    from the PDF document. Ensure that the questions are relevant and the answers
    are accurate based on the extracted content.
  expected_output: A set of {questions_count} questions along with their corresponding
    answers that are derived from the key facts extracted from the PDF document {filename}.
  async_execution: false
  agent: question_generator
fact_check_questions_and_answers_task:
  description: Validate all generated questions and answers for accuracy. Use the
    SerperDevTool to perform web searches and ensure that the information is correct
    and reliable.
  expected_output: A report detailing the validation process of the generated questions
    and answers, indicating which ones are accurate and which ones require corrections.
  async_execution: false
  agent: fact_checker
